export const editorConfig = {
    placeholder: '펀딩을 소개해주세요.',
    toolbar: {
        items: [
            "heading",
            "|",
            "link",
            "imageUpload",
            "mediaEmbed",
            "imageInsert",
            "|",
            "horizontalLine",
            "|",
            "findAndReplace",
            "undo",
            "redo",
            "-",
            "bold",
            "italic",
            "fontSize",
            "fontFamily",
            "fontColor",
            "fontBackgroundColor",
            "|",
            "alignment",
            "outdent",
            "indent",
            "|",
            "bulletedList",
            "numberedList",
            "blockQuote",
        ],
        shouldNotGroupWhenFull: true,
    },
    language: "ko",
    image: {
        toolbar: [
            "imageTextAlternative",
            "toggleImageCaption",
            "imageStyle:inline",
            "imageStyle:block",
            "imageStyle:side",
            "linkImage",
        ],
    },
}